### ISSUE TITLE
Is this complete?

### ISSUE THREAD

**Issue by ryantheleach** [AndrioCelos/MinecraftJsonSchemas#1]
Hey! thanks for making this.

But I have a few queries.

1. Can you please license the project? (Preferably such that I can use it, but even a license saying I can't would be good!)

2. Is it up to date / is there any known issues?

3. How does it compare to https://github.com/Levertion/minecraft-json-schemas

4. What draft version of JSON Schema's does it use?

**Comment by AndrioCelos** [comment]
Hi, Ryan. Sorry for not getting back to you on Discord; you may reach out to me again if you want.

1. Of course. I'm curious as to how you're going to include it in something, though.
2. I haven't updated it for 1.13 yet.
3. I wasn't aware of that project when I started on this. My repository was written from the ground up for Visual Studio Code, and I also plan to keep the documents for older versions of Minecraft in separate directories. As such, you may see nicer results from auto-completion in Visual Studio Code.
4. I use JSON Schema Draft 6, as Visual Studio Code currently does not support Draft 7 (see Microsoft/vscode#46322)

**Comment by ryantheleach** [comment]
1. Essentially I wanted to be able to package it, and use it as a dependency.
2. I'm targeting 1.12 currently.

My current side-project, is to create a Gradle build script, that creates a pipeline for compositing minecraft resource pack assets into a final resource pack.

I've got no idea how far I want to take this, but at the moment the current plan is just, "copy stuff to a folder, validate the JSON + file references, zip it"

Future work that I'd consider if someone helped out (but is too advanced for me currently) is creating 'parent' resource packs, with children overriding sections of them in some form. pre-processing of assets, for scaling or brevity in defining repetitive JSON (think the damage values on hoes) or sites like 'painterly pack' or 'Vanilla Tweaks' that allow you to 'patch' your resource pack with other variants.

Currently that project is licensed under MIT, so I'm currently researching whether I can use your license, and what effects the NC aspect has over projects created with my pipeline, if I choose to use your work.

It's my suspicion, that your license may be flat incompatible with mine, so I may need to split my project or re-license it to get it compatible.

The part that I'm most concerned about however, is the 'virality' of the NC clause.

If I use a JSON Schema as a component in my tool, to validate the licensing, does my tool need the NC clause.

If it does/doesn't Do the resource packs (who often get hosted on Curse, which is ad revenue driven + ad.fly links) have to be NC.

My suspicion is they don't. But I'm currently looking into it. https://opensource.stackexchange.com/questions/7285/creativecommons-by-nc-sa-4-0-non-commercial-virality
